[package]
name = "ratatui_rb"
version = "0.1.0"
edition = "2021"
authors = ["Guilherme Moretti <guilherme.moretti@powerhrg.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
crossterm = "0.27.0"
magnus = { version = "0.4" }
ratatui = "0.25.0"
